import streamlit as st
import base64

TRANSLATIONS = {
    "en": {
        "AI Farm Assistant": "AI Farm Assistant",
        "Farm Tools": "Farm Tools",
        "Crop Prediction": "Crop Prediction",
        "Fertilizer Recommendation": "Fertilizer Recommendation",
        "Plant Knowledge Center 📖": "Plant Knowledge Center 📖",
        "Choose Language": "Choose Language",
        "Choose Task": "Choose Task",
        "Speak now...": "Speak now...",
        "Please speak your input.": "Please speak your input.",
        "No speech detected. Please try again.": "No speech detected. Please try again.",
        "Could not understand audio. Please try again.": "Could not understand audio. Please try again.",
        "Recommended Crop": "Recommended Crop",
        "Recommended Fertilizer": "Recommended Fertilizer",
        "Crop Prediction Input": "Crop Prediction Input",
        "Fertilizer Recommendation Input": "Fertilizer Recommendation Input",
        "Speak or type values for N,P,K,Temperature,Humidity,pH,Rainfall separated by commas.": "Speak or type values for N,P,K,Temperature,Humidity,pH,Rainfall separated by commas.",
        "Speak or type values for Temperature,Humidity,Moisture,SoilType,CropType,N,K,P separated by commas.": "Speak or type values for Temperature,Humidity,Moisture,SoilType,CropType,N,K,P separated by commas.",
        "Enter values (e.g., 10, 20, 30, 25.5, 65, 7.2, 200)": "Enter values (e.g., 10, 20, 30, 25.5, 65, 7.2, 200)",
        "Enter values (e.g., 28, 80, 40, clay, maize, 20, 10, 5)": "Enter values (e.g., 28, 80, 40, clay, maize, 20, 10, 5)",
        "Submit": "Submit",
        "Start Listening": "Start Listening",
        "Please enter or speak values.": "Please enter or speak values.",
        "Sorry, no information available for this plant.": "Sorry, no information available for this plant.",
        "An unexpected error occurred while fetching information.": "An unexpected error occurred while fetching information.",
        "Sorry, no information available for this topic.": "Sorry, no information available for this topic.",
        "Description": "Description",
        "Health Benefits": "Health Benefits",
        "Medicinal/Traditional Uses": "Medicinal/Traditional Uses",
        "Season & Availability": "Season & Availability",
        "Storage & Usage": "Storage & Usage",
        "Nutrients": "Nutrients",
        "Speak or type the name of a plant to learn about it.": "Speak or type the name of a plant to learn about it.",
        "Enter plant name": "Enter plant name",
        "Please enter a plant name.": "Please enter a plant name.",
    },
    "te": {
        "AI Farm Assistant": "AI ఫార్మ్ అసిస్టెంట్",
        "Farm Tools": "వ్యవసాయ ఉపకరణాలు",
        "Crop Prediction": "పంటల అంచనా",
        "Fertilizer Recommendation": "ఎరువుల సిఫార్సు",
        "Plant Knowledge Center 📖": "మొక్కల సమాచార కేంద్రం 📖",
        "Choose Language": "భాషను ఎంచుకోండి",
        "Choose Task": "పనిని ఎంచుకోండి",
        "Speak now...": "ఇప్పుడు మాట్లాడండి...",
        "Please speak your input.": "దయచేసి మీ ఇన్పుట్ చెప్పండి.",
        "No speech detected. Please try again.": "వాయిస్ కనుగొనబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
        "Could not understand audio. Please try again.": "వాయిస్ అర్థం కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
        "Recommended Crop": "సిఫార్సు చేయబడిన పంట",
        "Recommended Fertilizer": "సిఫార్సు చేయబడిన ఎరువు",
        "Crop Prediction Input": "పంటల అంచనా ఇన్పుట్",
        "Fertilizer Recommendation Input": "ఎరువుల సిఫార్సు ఇన్పుట్",
        "Speak or type values for N,P,K,Temperature,Humidity,pH,Rainfall separated by commas.": "N, P, K, ఉష్ణోగ్రత, తేమ, pH, వర్షపాతం కోసం విలువలని కామాలతో వేరు చేసి మాట్లాడండి లేదా టైప్ చేయండి.",
        "Speak or type values for Temperature,Humidity,Moisture,SoilType,CropType,N,K,P separated by commas.": "ఉష్ణోగ్రత, తేమ, తేమ శాతం, నేల రకం, పంట రకం, N, K, P కోసం విలువలని కామాలతో వేరు చేసి మాట్లాడండి లేదా టైప్ చేయండి.",
        "Enter values (e.g., 10, 20, 30, 25.5, 65, 7.2, 200)": "విలువలని నమోదు చేయండి (ఉదా: 10, 20, 30, 25.5, 65, 7.2, 200)",
        "Enter values (e.g., 28, 80, 40, clay, maize, 20, 10, 5)": "విలువలని నమోదు చేయండి (ఉదా: 28, 80, 40, బంకమట్టి, మొక్కజొన్న, 20, 10, 5)",
        "Submit": "సమర్పించండి",
        "Start Listening": "వాయిస్ వినడం ప్రారంభించండి",
        "Please enter or speak values.": "దయచేసి విలువలను నమోదు చేయండి లేదా మాట్లాడండి.",
        "Sorry, no information available for this plant.": "క్షమించండి, ఈ మొక్కకు సమాచారం అందుబాటులో లేదు.",
        "An unexpected error occurred while fetching information.": "సమాచారాన్ని పొందేటప్పుడు ఊహించని లోపం జరిగింది.",
        "Sorry, no information available for this topic.": "క్షమించండి, ఈ అంశానికి సమాచారం అందుబాటులో లేదు.",
        "Description": "వివరణ",
        "Health Benefits": "ఆరోగ్య ప్రయోజనాలు",
        "Medicinal/Traditional Uses": "ఔషధ/సాంప్రదాయ ఉపయోగాలు",
        "Season & Availability": "సీజన్ & లభ్యత",
        "Storage & Usage": "నిల్వ & ఉపయోగం",
        "Nutrients": "పోషకాలు",
        "Speak or type the name of a plant to learn about it.": "మొక్క గురించి తెలుసుకోవడానికి దాని పేరును మాట్లాడండి లేదా టైప్ చేయండి.",
        "Enter plant name": "మొక్క పేరును నమోదు చేయండి",
        "Please enter a plant name.": "దయచేసి మొక్క పేరును నమోదు చేయండి.",
    },
    "hi": {
        "AI Farm Assistant": "एआई फार्म असिस्टेंट",
        "Farm Tools": "कृषि उपकरण",
        "Crop Prediction": "फसल का पूर्वानुमान",
        "Fertilizer Recommendation": "उर्वरक की सिफारिश",
        "Plant Knowledge Center 📖": "पौधे ज्ञान केंद्र 📖",
        "Choose Language": "भाषा चुनें",
        "Choose Task": "कार्य चुनें",
        "Speak now...": "अभी बोलें...",
        "Please speak your input.": "कृपया अपना इनपुट बोलें।",
        "No speech detected. Please try again.": "कोई आवाज नहीं मिली। कृपया पुनः प्रयास करें।",
        "Could not understand audio. Please try again.": "ऑडियो समझ नहीं आया। कृपया पुनः प्रयास करें।",
        "Recommended Crop": "अनुशंसित फसल",
        "Recommended Fertilizer": "अनुशंसित उर्वरक",
        "Crop Prediction Input": "फसल पूर्वानुमान इनपुट",
        "Fertilizer Recommendation Input": "उर्वरक सिफारिश इनपुट",
        "Speak or type values for N,P,K,Temperature,Humidity,pH,Rainfall separated by commas.": "N, P, K, तापमान, आर्द्रता, pH, और वर्षा के लिए मानों को कॉमा से अलग करके बोलें या टाइप करें।",
        "Speak or type values for Temperature,Humidity,Moisture,SoilType,CropType,N,K,P separated by commas.": "तापमान, आर्द्रता, नमी, मिट्टी का प्रकार, फसल का प्रकार, N, K, P के लिए मानों को कॉमा से अलग करके बोलें या टाइप करें।",
        "Enter values (e.g., 10, 20, 30, 25.5, 65, 7.2, 200)": "मान दर्ज करें (उदाहरण: 10, 20, 30, 25.5, 65, 7.2, 200)",
        "Enter values (e.g., 28, 80, 40, clay, maize, 20, 10, 5)": "मान दर्ज करें (उदाहरण: 28, 80, 40, चिकनी, मक्का, 20, 10, 5)",
        "Submit": "जमा करें",
        "Start Listening": "सुनना शुरू करें",
        "Please enter or speak values.": "कृपया मान दर्ज करें या बोलें।",
        "Sorry, no information available for this plant.": "क्षमा करें, इस पौधे के लिए कोई जानकारी उपलब्ध नहीं है।",
        "An unexpected error occurred while fetching information.": "जानकारी प्राप्त करते समय एक अप्रत्याशित त्रुटि हुई।",
        "Sorry, no information available for this topic.": "क्षमा करें, इस विषय पर कोई जानकारी उपलब्ध नहीं है।",
        "Description": "विवरण",
        "Health Benefits": "स्वास्थ्य लाभ",
        "Medicinal/Traditional Uses": "औषधीय/पारंपरिक उपयोग",
        "Season & Availability": "मौसम और उपलब्धता",
        "Storage & Usage": "भंडारण और उपयोग",
        "Nutrients": "पोषक तत्व",
        "Speak or type the name of a plant to learn about it.": "किसी पौधे के बारे में जानने के लिए उसका नाम बोलें या टाइप करें।",
        "Enter plant name": "पौधे का नाम दर्ज करें",
        "Please enter a plant name.": "कृपया एक पौधे का नाम दर्ज करें।",
    },
    "ta": {
        "AI Farm Assistant": "AI பண்ணை உதவியாளர்",
        "Farm Tools": "பண்ணை கருவிகள்",
        "Crop Prediction": "பயிர் கணிப்பு",
        "Fertilizer Recommendation": "உரம் பரிந்துரை",
        "Plant Knowledge Center 📖": "செடி தகவல் மையம் 📖",
        "Choose Language": "மொழியைத் தேர்வு செய்யவும்",
        "Choose Task": "பணியைத் தேர்வு செய்யவும்",
        "Speak now...": "இப்போது பேசுங்கள்...",
        "Please speak your input.": "தயவுசெய்து உங்கள் உள்ளீட்டைப் பேசுங்கள்.",
        "No speech detected. Please try again.": "குரல் கண்டறியப்படவில்லை. மீண்டும் முயற்சிக்கவும்.",
        "Could not understand audio. Please try again.": "குரலை புரிந்துகொள்ள முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
        "Recommended Crop": "பரிந்துரைக்கப்பட்ட பயிர்",
        "Recommended Fertilizer": "பரிந்துரைக்கப்பட்ட உரம்",
        "Crop Prediction Input": "பயிர் கணிப்பு உள்ளீடு",
        "Fertilizer Recommendation Input": "உரம் பரிந்துரை உள்ளீடு",
        "Speak or type values for N,P,K,Temperature,Humidity,pH,Rainfall separated by commas.": "N,P,K, வெப்பநிலை, ஈரப்பதம், pH, மழைப்பொழிவுக்கான மதிப்புகளை கமா மூலம் பிரித்துப் பேசவும் அல்லது தட்டச்சு செய்யவும்.",
        "Speak or type values for Temperature,Humidity,Moisture,SoilType,CropType,N,K,P separated by commas.": "வெப்பநிலை, ஈரப்பதம், ஈரப்பதம், மண் வகை, பயிர் வகை, N, K, Pக்கான மதிப்புகளை கமா மூலம் பிரித்துப் பேசவும் அல்லது தட்டச்சு செய்யவும்.",
        "Enter values (e.g., 10, 20, 30, 25.5, 65, 7.2, 200)": "மதிப்புகளை உள்ளிடவும் (எ.கா., 10, 20, 30, 25.5, 65, 7.2, 200)",
        "Enter values (e.g., 28, 80, 40, clay, maize, 20, 10, 5)": "மதிப்புகளை உள்ளிடவும் (எ.கா., 28, 80, 40, களிமண், மக்காச்சோளம், 20, 10, 5)",
        "Submit": "சமர்ப்பி",
        "Start Listening": "கேட்கத் தொடங்கு",
        "Please enter or speak values.": "தயவுசெய்து மதிப்புகளை உள்ளிடவும் அல்லது பேசவும்.",
        "Sorry, no information available for this plant.": "மன்னிக்கவும், இந்த தாவரத்திற்கு எந்த தகவலும் இல்லை.",
        "An unexpected error occurred while fetching information.": "தகவலைப் பெறும்போது எதிர்பாராத பிழை ஏற்பட்டது.",
        "Sorry, no information available for this topic.": "மன்னிக்கவும், இந்த தலைப்புக்கு எந்த தகவலும் இல்லை.",
        "Description": "விளக்கம்",
        "Health Benefits": "ஆரோக்கிய நன்மைகள்",
        "Medicinal/Traditional Uses": "மருத்துவ/பாரம்பரிய பயன்கள்",
        "Season & Availability": "பருவம் & கிடைக்கும் தன்மை",
        "Storage & Usage": "சேமிப்பு & பயன்பாடு",
        "Nutrients": "ஊட்டச்சத்துக்கள்",
        "Speak or type the name of a plant to learn about it.": "ஒரு செடியைப் பற்றி அறிய அதன் பெயரைப் பேசவும் அல்லது தட்டச்சு செய்யவும்.",
        "Enter plant name": "செடியின் பெயரை உள்ளிடவும்",
        "Please enter a plant name.": "தயவுசெய்து ஒரு செடியின் பெயரை உள்ளிடவும்.",
    }
}


def get_translated_label(label, lang_code):
    return TRANSLATIONS.get(lang_code, {}).get(label, label)

def set_background(image_file):
    with open(image_file, "rb") as f:
        img_data = f.read()
    b64_encoded = base64.b64encode(img_data).decode()
    
    css = f"""
    <style>
    .stApp {{
        background-image: url("data:image/jpeg;base64,{b64_encoded}");
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
    }}
    </style>
    """
    st.markdown(css, unsafe_allow_html=True)